---
# tasks file for consul
    - name: apt install unzip
      become: true
      apt: 
        name: unzip
        state: present

    - name: download
      ansible.builtin.get_url:
        url: "https://hashicorp-releases.yandexcloud.net/consul/1.18.0/consul_1.18.0_linux_amd64.zip"
        dest: /tmp/consul_1.18.0_linux_amd64.zip
        mode: '0666'

    - name: unzip
      become: true
      shell: "unzip /tmp/consul_1.18.0_linux_amd64.zip -d /usr/bin/"
      ignore_errors: true

    - name: user consul
      ansible.builtin.user:
        name: consul
        comment: for consul

    - name: Create /var/lib/consul
      ansible.builtin.file:
        path: /var/lib/consul
        owner: consul
        group: consul
        state: directory
        mode: '0755'

    - name: Create /etc/consul.d
      ansible.builtin.file:
        owner: consul
        group: consul
        path: /etc/consul.d
        state: directory
        mode: '0755'

    - name: consul key
      ansible.builtin.shell:
        cmd: consul keygen
      register: consul_token
      run_once: true
    
    - name: check
      debug:
        msg: "{{ consul_token.stdout }}"


    - name: "Add consul_token"
      add_host:
        name:   "consul"
        consul_token:  "{{ consul_token.stdout }}"


    - name: Copy config
      become: true
      ansible.builtin.template:
        src: config.json.j2
        mode: "0644"
        dest: "/etc/consul.d/config.json"

    - name: Copy service
      become: true
      ansible.builtin.copy:
        src: consul.service
        dest: "/etc/systemd/system/consul.service"

    - name: Just force systemd to reread configs
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Enable nginx service
      ansible.builtin.systemd_service:
        name: consul.service
        enabled: true
        state: started