---
# tasks file for consul
    - name: apt install unzip
      become: true
      apt: 
        name: unzip
        state: present

    - name: download
      ansible.builtin.get_url:
        url: "https://hashicorp-releases.yandexcloud.net/consul/1.18.0/consul_1.18.0_linux_amd64.zip"
        dest: /tmp/consul_1.18.0_linux_amd64.zip
        mode: '0666'

    - name: Unzip
      become: true
      shell: "unzip /tmp/consul_1.18.0_linux_amd64.zip -d /usr/bin/"
      ignore_errors: true

    - name: User consul
      ansible.builtin.user:
        name: consul
        comment: for consul

    - name: Create /var/lib/consul
      ansible.builtin.file:
        path: /var/lib/consul
        owner: consul
        group: consul
        state: directory
        mode: '0755'

    - name: Create /etc/consul.d
      ansible.builtin.file:
        owner: consul
        group: consul
        path: /etc/consul.d
        state: directory
        mode: '0755'

    - name: Consul key
      ansible.builtin.shell:
        cmd: consul keygen
      register: consul_token
      when: "'master1' in ansible_hostname"

    # - name: check
    #   debug:
    #     msg: "{{ consul_token.stdout }}"

    - name: write elastic to file for kibana web-logging
      ansible.builtin.copy:
        content: "{{ consul_token.stdout }}"
        dest: "/tmp/consul.txt"
      when: "'master1' in ansible_hostname"

    - name: Copy pass elastic to master-ansible
      ansible.builtin.fetch:
        src:  /tmp/consul.txt
        dest: "{{ local_dir }}/consul.txt"
        flat: true
      when: "'master1' in ansible_hostname"

    - name: get content of remote file
      set_fact:
        readme_contents: "{{ lookup('file', '/Users/joos/Desktop/very_secure_dir/consul.txt') }}"
      register: remote_content_encoded

    # - debug:
    #     msg: "{{ remote_content_encoded.ansible_facts.readme_contents }}"

    - name: Add consul_token
      add_host:
        name: "consul"
        consul_token:  "{{ remote_content_encoded.ansible_facts.readme_contents }}"

    - name: Copy server config
      become: true
      ansible.builtin.template:
        src: config-server.json.j2
        mode: "0644"
        dest: "/etc/consul.d/config.json"
      when: "'master' in ansible_hostname"

    - name: Copy agent config
      become: true
      ansible.builtin.template:
        src: config-agent.json.j2
        mode: "0644"
        dest: "/etc/consul.d/config.json"
      when: "'agent' in ansible_hostname"

    - name: Copy service
      become: true
      ansible.builtin.copy:
        src: consul.service
        dest: "/etc/systemd/system/consul.service"

    - name: Just force systemd to reread configs
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Enable nginx service
      ansible.builtin.systemd_service:
        name: consul.service
        enabled: true
        state: started